### ISSUE TITLE
Heroku Deployment Error - On hitting the "/" route of client, it somehow gets back to "/" of server.

### ISSUE THREAD

**Issue by tarunnsingh** [tarunnsingh/twitt-dashboard#1]
### What is the Error?
The project when deployed to Heroku, doesn't load the clients home page (matching to localhost:3000, when running locally) instead fires up the servers home page (localhost:5000, when running locally).

**Comment by jasbindar-singh** [comment]
Check this should help https://docs.netlify.com/configure-builds/get-started/#basic-build-settings

**Comment by ccsCoder** [comment]
@tarunnsingh If I remember correctly, heroku requires you to use `process.env.PORT` and then fallback to a predefined port.

**Comment by tarunnsingh** [comment]
@ccsCoder  But I don't think we need to explicitly mention the port in React, when deploying to Heroku?

**Comment by tarunnsingh** [comment]
**Voila I figured it out!!**
And it is so silly mistake.

To anyone coming here later, if you are using the MERN stack, and deploying it, then make sure you do not have any matching routes in the client and server.
Basically, in the **client side** if you have routes like these:
- "/"
- "/login"
- "/home" etc.
You are not allowed to have them in the server too.

Because when deployed to production the client is basically built and served as static files.
```javascript
if (process.env.NODE_ENV === "production") {
  app.use(express.static("client/build"));
  app.get("*", (req, res) => {
    res.sendFile(path.resolve(__dirname, "client", "build", "index.html"));
  });
}
```
**The app.get("*") will pass any non-matching request to the client.
But if you already have those routes in the server then this won't happen and you'd just be served that route from the server itself.**
